# Generated by Django 5.0.4 on 2026-02-14 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_plan_alter_material_lesson_classsession'),
        ('users', '0002_alter_user_groups_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_attended', to='users.student', verbose_name='Aluno'),
        ),
    ]
