# Generated by Django 5.0.4 on 2026-02-14 05:58

import users.models
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_groups_alter_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', users.models.ProfessorManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': "User's", 'verbose_name_plural': "User's"},
        ),
        migrations.AlterField(
            model_name='student',
            name='document_id',
            field=models.CharField(max_length=14, unique=True, validators=[users.validators.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[users.validators.validate_phone], verbose_name='Telefone (com DDD)'),
        ),
    ]
